services:
  server:
    build: "./server"
    ports:
      - "3000:3000"
    volumes:
      - ./server/src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
  client:
    build: "./client"
    ports:
      - "3001:3001"
    volumes:
      - ./client/src:/app/src
      - ./client/index.html:/app/index.html
    environment:
      - CHOKIDAR_USEPOLLING=true
